### ISSUE TITLE
How to simulate warthog in gazebo

### ISSUE THREAD

**Issue by EdnilsonAraujo** [warthog-cpr/warthog_simulator#2]
Hello. I'm trying to simulate the warthog in the gazebo, but since I'm a newbie, I'm having difficulties. Is there any tutorial that can explain how to do this simulation? Thank you for your help.

**Comment by ibaranov-cp** [comment]
1. Create a catkin_ws as usual (lots of tutorials online)
2. Ensure you have the warthog, warthog_desktop, warthog_simulator packages cloned
3. Run rosdep against the cloned packages
4. Build your workspace, source it
5. roslaunch warthog_gazebo warthog_world.launch

Cheers!

**Comment by EdnilsonAraujo** [comment]
Dear Ilia Baranov, thank you for your help. I created the work space and already downloaded the packages (steps 1 and 2). I do not know how to perform steps 3 and 4. What ws location do I put the downloaded packages? Sorry for the questions so simple, is that I'm really newbie with ROS

**Comment by 9leben** [comment]
Hi Ednilson,

This should help.

Ivan

Warthog base installation:

# cd to home directory
cd ~

# create workspace
mkdir -p warthog_ws/src
cd warthog_ws/src/
catkin_init_workspace
cd ..
catkin_make

# source path
source devel/setup.bash

# check the current workspace is added to the path
echo $CMAKE_PREFIX_PATH

# clone packages
sudo apt-get update
# you should be in ~/warthog_ws…
cd src
git clone https://github.com/warthog-cpr/warthog.git <https://github.com/warthog-cpr/warthog.git>
git clone https://github.com/warthog-cpr/warthog_simulator.git <https://github.com/warthog-cpr/warthog_simulator.git>
git clone https://github.com/warthog-cpr/warthog_desktop.git <https://github.com/warthog-cpr/warthog_desktop.git>
cd ..
rosdep install --from-paths src --ignore-src --rosdistro=$ROS_DISTRO -y
catkin_make

Ejecutar Gazebo (en otro terminal):

cd ~/warthog_ws
source devel/setup.bash
roslaunch warthog_gazebo warthog_world.launch

Ejecutar Rviz (en otro terminal):

cd ~/warthog_ws
source devel/setup.bash
roslaunch warthog_viz view_robot.launch

**Comment by EdnilsonAraujo** [comment]
Dear Ilia Baranov, thank you very much for the support. I created the ws, and downloaded the packages. When I run the catkin_make command, after "rosdep install --from-paths src --ignore-src --rosdistro = $ ROS_DISTRO -y" I get many errors and the gazebo does not show the simulation. What can be wrong? I'm using 7 gazebo and ROS kinetic. Sorry if I'm bothering you too much.

**Comment by 9leben** [comment]
Sorry I didn’t noticed that. It looks like the warthog has only been released into ROS Indigo.

I might be mistaken though, so you better wait for a response from Clearpath. 

I have it running with Indigo, but Gazebo version there is much older.

**Comment by EdnilsonAraujo** [comment]
Dear 9leben, pardon for my confusion. I thought I was talking to Ilia Baranov. 
Your help was very valuable. I am debugging the code. I am also hoping that someone else will come to help me.

**Comment by EdnilsonAraujo** [comment]
Success! I was able to run the simulation. I needed to enable the C ++ 11 option in CMake. Thank you Ilia Baranov and 9leben. I could not have done it without your help.

**Comment by ibaranov-cp** [comment]
Great stuff! :)

We will be releasing Kinetic versions (and Lunar, etc) soon
