### ISSUE TITLE
Laser setting doesn't seem to do anything?

### ISSUE THREAD

**Issue by ibaranov-cp** [warthog-cpr/warthog_simulator#3]
https://github.com/warthog-cpr/warthog_simulator/blob/d58bcf9813fc32c5ec31e9332e96434e2f21dd23/warthog_gazebo/launch/warthog_world.launch#L9

Or perhaps there is a rosdep that's not listed to ensure this works?

Cheers

**Comment by dniewinski** [comment]
This unnecessary argument has been removed

**Comment by ibaranov-cp** [comment]
Thanks! 👍
