### ISSUE TITLE
Resource not found: warthog_description

### ISSUE THREAD

**Issue by abdul-mannan-khan** [warthog-cpr/warthog_simulator#4]
Dear ClearPath, 

Thank You so much for this development. 
I am facing a problem in launching warthog_simulator. I am getting error 

`Resource not found: warthog_description`

I appreciate your kind response.

I am using Linux 18.04 with ROS Melodic.  

Thank You.

**Comment by tonybaltovski** [comment]
Did you install `warthog_description`?

**Comment by abdul-mannan-khan** [comment]
No. I just clonned this package.  Please, tell me how can I install it? Thank You for your time.

**Comment by tonybaltovski** [comment]
Clone `https://github.com/warthog-cpr/warthog` as well.
